### ISSUE TITLE
[Feature Request] Sort "Last Updated" only by version selected

### ISSUE THREAD

**Issue by Foreck1** [SuperStormer/cf-search#12] opened 2023-10-18 16:34 UTC
Currently, sorting for "last updated" will sort by projects that have had any version uploaded to their CF. It would be **huge** for older versions to finally be able to search **relevant** mods if it only showed last updates for the actual version selected, instead of the whole project.

**Comment by SuperStormer** [comment] 2023-10-18 16:46
dupe of #1

**Closed as completed by SuperStormer** 2023-10-18 16:46 UTC
